package com.webServiceCDome;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RoleServiceImplService service = new RoleServiceImplService();
 * RoleServiceImpl portType = service.getRoleServiceImplPort();
 * portType.getDepartment(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RoleServiceImplService", targetNamespace = "http://webService.com/", wsdlLocation = "http://192.20.1.89:8788/RoleServiceImpl?wsdl")
public class RoleServiceImplService extends Service {

	private final static URL ROLESERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.webServiceCDome.RoleServiceImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.webServiceCDome.RoleServiceImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://192.20.1.89:8788/RoleServiceImpl?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://192.20.1.89:8788/RoleServiceImpl?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ROLESERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public RoleServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RoleServiceImplService() {
		super(ROLESERVICEIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://webService.com/", "RoleServiceImplService"));
	}

	/**
	 * 
	 * @return returns RoleServiceImpl
	 */
	@WebEndpoint(name = "RoleServiceImplPort")
	public RoleServiceImpl getRoleServiceImplPort() {
		return super.getPort(new QName("http://webService.com/",
				"RoleServiceImplPort"), RoleServiceImpl.class);
	}

}
