
package com.webservice.client.constructor;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-04-29T14:56:19.429+08:00
 * Generated source version: 2.7.16
 * 
 */
public final class TJWebServiceSoap_TJWebServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "TJWebService");

    private TJWebServiceSoap_TJWebServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TJWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TJWebService ss = new TJWebService(wsdlURL, SERVICE_NAME);
        TJWebServiceSoap port = ss.getTJWebServiceSoap12();  
        
        {
        System.out.println("Invoking getSingleCorpRegPerson...");
        java.lang.String _getSingleCorpRegPerson_corpName = "";
        java.lang.String _getSingleCorpRegPerson_corpCode = "";
        java.lang.String _getSingleCorpRegPerson__return = port.getSingleCorpRegPerson(_getSingleCorpRegPerson_corpName, _getSingleCorpRegPerson_corpCode);
        System.out.println("getSingleCorpRegPerson.result=" + _getSingleCorpRegPerson__return);


        }

        System.exit(0);
    }

}
