package com.webservice.client.constructor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-04-29T14:56:19.524+08:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TJWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TJWebServiceSoap {

    @WebResult(name = "GetSingleCorpRegPersonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSingleCorpRegPerson", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.constructor.GetSingleCorpRegPerson")
    @WebMethod(operationName = "GetSingleCorpRegPerson", action = "http://tempuri.org/GetSingleCorpRegPerson")
    @ResponseWrapper(localName = "GetSingleCorpRegPersonResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.client.constructor.GetSingleCorpRegPersonResponse")
    public java.lang.String getSingleCorpRegPerson(
        @WebParam(name = "corpName", targetNamespace = "http://tempuri.org/")
        java.lang.String corpName,
        @WebParam(name = "corpCode", targetNamespace = "http://tempuri.org/")
        java.lang.String corpCode
    );
}
