package com.webservice.client.constructor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-04-29T14:56:19.536+08:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TJWebServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TJWebServiceHttpPost {

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetSingleCorpRegPerson")
    public java.lang.String getSingleCorpRegPerson(
        @WebParam(partName = "corpName", name = "corpName", targetNamespace = "http://tempuri.org/")
        java.lang.String corpName,
        @WebParam(partName = "corpCode", name = "corpCode", targetNamespace = "http://tempuri.org/")
        java.lang.String corpCode
    );
}
