
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.webservice.client.constructor;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2016-04-29T14:56:19.510+08:00
 * Generated source version: 2.7.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "TJWebService",
                      portName = "TJWebServiceHttpGet",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://192.20.1.43:9090/TJWebService.asmx?wsdl",
                      endpointInterface = "com.webservice.client.constructor.TJWebServiceHttpGet")
                      
public class TJWebServiceHttpGetImpl implements TJWebServiceHttpGet {

    private static final Logger LOG = Logger.getLogger(TJWebServiceHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see com.webservice.client.constructor.TJWebServiceHttpGet#getSingleCorpRegPerson(java.lang.String  corpName ,)java.lang.String  corpCode )*
     */
    public java.lang.String getSingleCorpRegPerson(java.lang.String corpName,java.lang.String corpCode) { 
        LOG.info("Executing operation getSingleCorpRegPerson");
        System.out.println(corpName);
        System.out.println(corpCode);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
