
package ws.client.tenderinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "InfoSoap", targetNamespace = "http://tempuri.org/")
public interface InfoSoap {


    /**
     * 
     * @param s
     * @param line
     * @return
     *     returns ws.client.tenderinfo.GetBidNoticeListResponse.GetBidNoticeListResult
     */
    @WebMethod(operationName = "GetBidNoticeList", action = "http://tempuri.org/GetBidNoticeList")
    @WebResult(name = "GetBidNoticeListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBidNoticeList", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidNoticeList")
    @ResponseWrapper(localName = "GetBidNoticeListResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidNoticeListResponse")
    public ws.client.tenderinfo.GetBidNoticeListResponse.GetBidNoticeListResult getBidNoticeList(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s,
        @WebParam(name = "line", targetNamespace = "http://tempuri.org/")
        int line);

    /**
     * 
     * @param s
     * @param tenderNum
     * @return
     *     returns ws.client.tenderinfo.GetBidNoticeInfoResponse.GetBidNoticeInfoResult
     */
    @WebMethod(operationName = "GetBidNoticeInfo", action = "http://tempuri.org/GetBidNoticeInfo")
    @WebResult(name = "GetBidNoticeInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBidNoticeInfo", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidNoticeInfo")
    @ResponseWrapper(localName = "GetBidNoticeInfoResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidNoticeInfoResponse")
    public ws.client.tenderinfo.GetBidNoticeInfoResponse.GetBidNoticeInfoResult getBidNoticeInfo(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s,
        @WebParam(name = "TenderNum", targetNamespace = "http://tempuri.org/")
        String tenderNum);

    /**
     * 
     * @param s
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetBidNoticeListCount", action = "http://tempuri.org/GetBidNoticeListCount")
    @WebResult(name = "GetBidNoticeListCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBidNoticeListCount", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidNoticeListCount")
    @ResponseWrapper(localName = "GetBidNoticeListCountResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidNoticeListCountResponse")
    public int getBidNoticeListCount(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param s
     * @param fsectionid
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SetBidNoticeState", action = "http://tempuri.org/SetBidNoticeState")
    @WebResult(name = "SetBidNoticeStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetBidNoticeState", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.SetBidNoticeState")
    @ResponseWrapper(localName = "SetBidNoticeStateResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.SetBidNoticeStateResponse")
    public int setBidNoticeState(
        @WebParam(name = "fsectionid", targetNamespace = "http://tempuri.org/")
        String fsectionid,
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param s
     * @param line
     * @return
     *     returns ws.client.tenderinfo.GetBidPersonListResponse.GetBidPersonListResult
     */
    @WebMethod(operationName = "GetBidPersonList", action = "http://tempuri.org/GetBidPersonList")
    @WebResult(name = "GetBidPersonListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBidPersonList", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidPersonList")
    @ResponseWrapper(localName = "GetBidPersonListResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidPersonListResponse")
    public ws.client.tenderinfo.GetBidPersonListResponse.GetBidPersonListResult getBidPersonList(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s,
        @WebParam(name = "line", targetNamespace = "http://tempuri.org/")
        int line);

    /**
     * 
     * @param s
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetBidPersonListCount", action = "http://tempuri.org/GetBidPersonListCount")
    @WebResult(name = "GetBidPersonListCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBidPersonListCount", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidPersonListCount")
    @ResponseWrapper(localName = "GetBidPersonListCountResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetBidPersonListCountResponse")
    public int getBidPersonListCount(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param fid
     * @param s
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SetBidPersonState", action = "http://tempuri.org/SetBidPersonState")
    @WebResult(name = "SetBidPersonStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetBidPersonState", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.SetBidPersonState")
    @ResponseWrapper(localName = "SetBidPersonStateResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.SetBidPersonStateResponse")
    public int setBidPersonState(
        @WebParam(name = "fid", targetNamespace = "http://tempuri.org/")
        String fid,
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param s
     * @param fIdCertNo
     * @param fEntName
     * @return
     *     returns ws.client.tenderinfo.GetSLRYListResponse.GetSLRYListResult
     */
    @WebMethod(operationName = "GetSLRYList", action = "http://tempuri.org/GetSLRYList")
    @WebResult(name = "GetSLRYListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSLRYList", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetSLRYList")
    @ResponseWrapper(localName = "GetSLRYListResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetSLRYListResponse")
    public ws.client.tenderinfo.GetSLRYListResponse.GetSLRYListResult getSLRYList(
        @WebParam(name = "FIdCertNo", targetNamespace = "http://tempuri.org/")
        String fIdCertNo,
        @WebParam(name = "FEntName", targetNamespace = "http://tempuri.org/")
        String fEntName,
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param s
     * @param fIdCertNo
     * @param fEntName
     * @return
     *     returns ws.client.tenderinfo.GetTZZYListResponse.GetTZZYListResult
     */
    @WebMethod(operationName = "GetTZZYList", action = "http://tempuri.org/GetTZZYList")
    @WebResult(name = "GetTZZYListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTZZYList", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetTZZYList")
    @ResponseWrapper(localName = "GetTZZYListResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetTZZYListResponse")
    public ws.client.tenderinfo.GetTZZYListResponse.GetTZZYListResult getTZZYList(
        @WebParam(name = "FIdCertNo", targetNamespace = "http://tempuri.org/")
        String fIdCertNo,
        @WebParam(name = "FEntName", targetNamespace = "http://tempuri.org/")
        String fEntName,
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param s
     * @param fCorpCode
     * @param fName
     * @return
     *     returns ws.client.tenderinfo.GetAQSCXKZListResponse.GetAQSCXKZListResult
     */
    @WebMethod(operationName = "GetAQSCXKZList", action = "http://tempuri.org/GetAQSCXKZList")
    @WebResult(name = "GetAQSCXKZListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAQSCXKZList", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetAQSCXKZList")
    @ResponseWrapper(localName = "GetAQSCXKZListResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetAQSCXKZListResponse")
    public ws.client.tenderinfo.GetAQSCXKZListResponse.GetAQSCXKZListResult getAQSCXKZList(
        @WebParam(name = "FCorpCode", targetNamespace = "http://tempuri.org/")
        String fCorpCode,
        @WebParam(name = "FName", targetNamespace = "http://tempuri.org/")
        String fName,
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param s
     * @param fIdCertNo
     * @param fEntName
     * @return
     *     returns ws.client.tenderinfo.GetJLRYListResponse.GetJLRYListResult
     */
    @WebMethod(operationName = "GetJLRYList", action = "http://tempuri.org/GetJLRYList")
    @WebResult(name = "GetJLRYListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetJLRYList", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetJLRYList")
    @ResponseWrapper(localName = "GetJLRYListResponse", targetNamespace = "http://tempuri.org/", className = "ws.client.tenderinfo.GetJLRYListResponse")
    public ws.client.tenderinfo.GetJLRYListResponse.GetJLRYListResult getJLRYList(
        @WebParam(name = "FIdCertNo", targetNamespace = "http://tempuri.org/")
        String fIdCertNo,
        @WebParam(name = "FEntName", targetNamespace = "http://tempuri.org/")
        String fEntName,
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

}
