
package ws.client.tenderinfo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
* <p>
* An example of how this class may be used:
* <pre>
* Info service = new Info();
* InfoSoap portType = service.getInfoSoap();
* portType.getBidNoticeList(...);
* </pre>
* </p>
 * 
 */
@WebServiceClient(name = "Info", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.20.0.30:81/Info.asmx?wsdl")
public class Info
    extends Service
{

    private final static URL INFO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws.client.tenderinfo.Info.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws.client.tenderinfo.Info.class.getResource(".");
            url = new URL(baseUrl, "http://192.20.0.30:81/Info.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.20.0.30:81/Info.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INFO_WSDL_LOCATION = url;
    }

    public Info(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Info() {
        super(INFO_WSDL_LOCATION, new QName("http://tempuri.org/", "Info"));
    }

    /**
     * 
     * @return
     *     returns InfoSoap
     */
    @WebEndpoint(name = "InfoSoap")
    public InfoSoap getInfoSoap() {
        return super.getPort(new QName("http://tempuri.org/", "InfoSoap"), InfoSoap.class);
    }

    /**
     * 
     * @return
     *     returns InfoSoap
     */
    @WebEndpoint(name = "InfoSoap12")
    public InfoSoap getInfoSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "InfoSoap12"), InfoSoap.class);
    }

}
